sonar.projectKey=InseeFr_Impala
sonar.organization=inseefr
sonar.host.url=https://sonarcloud.io

# Project name & version
sonar.projectName=Impala
sonar.projectVersion=4.9.0

# Path to sources
sonar.sources=src
sonar.exclusions=src/**/*.spec.tsx, src/**/*.test.tsx

# Path to tests
sonar.test.inclusions=src/**/*.spec.tsx, src/**/*.test.tsx

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.spec.tsx, src/**/*.test.tsx

# Source encoding
sonar.sourceEncoding=UTF-8
