events {
    worker_connections  4096;  ## Default: 1024
}

http {
    types {
        module js;
    }
    include /etc/nginx/mime.types;

    server {
        listen 80;
        root /usr/share/nginx/html;
        gzip on;
        gzip_types text/css application/javascript application/json image/svg+xml;
        gzip_comp_level 9;
        etag on;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 443 ssl;
        root /usr/share/nginx/html;

        ssl_certificate /etc/nginx/ssl/nginx.crt;  # Chemin vers votre certificat SSL
        ssl_certificate_key /etc/nginx/ssl/nginx.key;  # Chemin vers votre clé SSL
        ssl_protocols TLSv1.2 TLSv1.3;  # Protocole SSL à utiliser
        ssl_ciphers HIGH:!aNULL:!MD5;

        gzip on;
        gzip_types text/css application/javascript application/json image/svg+xml;
        gzip_comp_level 9;
        etag on;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
