name: Release
on:
    release:
        types: [prereleased]
        branches:
            - migration_to_kube
        paths-ignore:
            - documentation/**
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [20]
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - run: yarn
            - run: yarn test --coverage --watch=false

    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract version
              run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  file: Dockerfile
                  tags: ghcr.io/inseefr/impala:${{ env.VERSION }}
